apiVersion: v1
kind: Service
metadata:
  name:  app-service
  namespace: {{.Values.namespace.name}}
spec:
  selector:
    app:  app-service
  type: LoadBalancer
  ports:
  - nodePort: {{.Values.service.nodePort}}
    port:  {{.Values.service.port}}
    targetPort:  {{.Values.service.targetPort}}